# -*- coding: utf-8 -*-
"""checkpoint3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yi8AnNNszok2mOa9OE4z77-LrRMi1j33
"""

x=int(input("donner un entier x")) #ex1
y=int(input("donner un entier y"))
z=int(input("donner un entier z"))
if y<x and z<x :
  print(x)
elif x<y and z<y :
  print(y)
else:
  print(z)

def calculation(a,b): #ex2
  print(a+b,a-b)

calculation(40,10)

def addition(list):  #EX4
  s=0
  for i in list:
    s=s+list[i]
  return(s)

def multiplication(list):
  r=0
  for i in list:
    r=r*t[i]
  return(r)

L=[1,2,4,9,5,10,22]
list2=[]

for i in range (len(L)):
  if i%2==0:
    print(i)

#EX4
words = [w for w in input("words: ").split("-")]

words.sort()

print("-".join(words))

#EX5
H=50
C=30
D=int(input("donner un entier D"))
def mafonction(C,D,H):
   Q=((2*C*D)/H)
print(Q)